version: '3'
services:
  pdf2image_service:
    build: ./services/PDF2Image-Service
    ports:
      - "5001:5001"

  image2text_service:
    build: ./services/Image2Text-Service
    ports:
      - "5002:5002"

  text2structure_service:
    build: ./services/Text2Structure-Service
    ports:
      - "5003:5003"

  vatinference_service:
    build: ./services/VATInference-Service
    ports:
      - "5004:5004"
